### ISSUE TITLE
Design and fabrication of test stand

### ISSUE THREAD

**Issue by shohei** [nakujaproject/intern#1]
This includes

- [x] Design and fabrication of the frame
- [x] Design and fabrication of thrust measurement circuit
- [x] Programming of microcontroller (#2)

**Comment by JeffMboya** [comment]
Test stand design completed. Fabrication set to begin.

**Comment by JeffMboya** [comment]
Test stand fabricated. First static firing test conducted. Modification to enhance safety to be made.
