### ISSUE TITLE
Research on payload camera

### ISSUE THREAD

**Issue by shohei** [nakujaproject/intern#10]
- Identify the specification of payload camera
- Identify the necessary system for the camera to be able to capture video during flight

**Comment by shohei** [comment]
Example payload camera from apogee
https://www.apogeerockets.com/Electronics-Payloads/Cameras/U-838-HD-Video-Camera

**Comment by 0x6f736f646f** [comment]
@oryankibandi I think you are done with this

**Comment by 0x6f736f646f** [comment]
@oryankibandi where have you reached on this?

**Comment by oryankibandi** [comment]
i am done. Will close this issue
