### ISSUE TITLE
Redefine N-1 airframe dimension

### ISSUE THREAD

**Issue by shohei** [nakujaproject/intern#16]
- [x] Adjust diameter depending on the diameter of SRM
- [x] Adjust diameter/length depending on the N-1 avionics bay

**Comment by 0x6f736f646f** [comment]
@1998-felix Provide the length and outside diameter of the SRM

**Comment by 0x6f736f646f** [comment]
#5  @Mike-Kimani Provide length and width of the avionics bay

**Comment by 0x6f736f646f** [comment]
Tentative the first design is at [here](https://github.com/nakujaproject/airframev1)

Also the open rocket simulation is at [here](https://github.com/nakujaproject/airframe_openrocket)

**Comment by 0x6f736f646f** [comment]
@dmashy and @shohei please check it out

> Tentative the first design is at [here](https://github.com/nakujaproject/airframev1)
> 
> Also the open rocket simulation is at [here](https://github.com/nakujaproject/airframe_openrocket)

**Comment by 0x6f736f646f** [comment]
Diameter is adjusted to 50mm

**Comment by 0x6f736f646f** [comment]
Diameter has been adjusted to 53
