### ISSUE TITLE
Finalize dimension and thrust of N-1 SRM

### ISSUE THREAD

**Issue by shohei** [nakujaproject/intern#17]
- [x] Finalize the diameter and length of N-1 SRM
  - necessary for the airframe team to work on the final N-1 airframe
- [x] Conclude the expected thrust of the motor
  - necessary to discuss the diameter of the access control area

**Comment by SammyOina** [comment]
The final dimensions are
- Length: 200mm
- Motor Diameter: 40mm
- Endcap Diameter: 50mm
- Motor weight: 300 - 400 grams
