### ISSUE TITLE
Programming of Arduino/Raspberry Pi to analyze thrust data

### ISSUE THREAD

**Issue by shohei** [nakujaproject/intern#2]
- [x] Development of PCB to measure thrust data (Loadcell, amplifier, microcontroller)
- [x] Upload measurement data automatically to Google drive (Use Raspberry Pi?)
- [x] VIsualization of thrust data using graph

**Comment by SammyOina** [comment]
The program to analyze the generated CSV is in [https://github.com/nakujaproject/thrust-analysis/blob/main/thrustAnalysis.ipynb](url)\
The PCB for loadcell amplifier (hx-711) is designed and is in the fusion team. Fabrication of the PCB is to be on Thursday\
The program for visualization and uploading the file to google drive is in [https://github.com/nakujaproject/thrust-analysis/blob/main/main.go](url)\
