### ISSUE TITLE
Altimeter-Research

### ISSUE THREAD

**Issue by willytounsi** [nakujaproject/intern#25]
Function 
Available altimeters on the market
Comparison:
- specifications
- Cost 
- Availability

**Comment by oryankibandi** [comment]
From the research done. modules which are exclusively altimeters such as Altimeter and MS5607 were not available in the local market. We resulted to pressure sensors from which we would calculate the altitude.
Some of the pressure sensors found locally include:

- MS5611-01BA03 - [https://www.pixelelectric.com/sensors/load-pressure-flow-vibration/load-pressure-force-flex-sensor/gy-63-ms5611-atmospheric-pressure-sensor/](url)
- GY-BME/P 280 - [https://www.pixelelectric.com/sensors/load-pressure-flow-vibration/load-pressure-force-flex-sensor/gy-bme-p-280-atmospheric-pressure-sensor/](url)
- BMP 180 - [https://www.pixelelectric.com/sensors/load-pressure-flow-vibration/load-pressure-force-flex-sensor/bmp180-barometric-pressure/](url)

All the modules are available locally. 
**MS5611-01BA03**
This is the most expensive at ksh. 1100 but also the most accurate.
Input voltage of 3V-5V
Resolution of 0.1m.
Interface- I2C and SPI
 
**GY-BME/P 280**
Cost-Ksh. 400
Interface - I2C and SPI
input voltage 3V - 5V
pressure - 300hPa to 1100hPa
altitude - 0ft to 30000ft
A tutorial on how to interface with arduino- [https://lastminuteengineers.com/bme280-arduino-tutorial/](url)

**BMP 180**
Cost - Ksh.350
Interface - I2C Pressure range 300-1100HPa
Resolution 0.25m
Range - upto 30000ft

Currently the BMP 180 is available. Research is ongoing to determine the best module for the job.
