### ISSUE TITLE
Accelerometer-Gyroscope Research

### ISSUE THREAD

**Issue by willytounsi** [nakujaproject/intern#26]
Function
Available accelerometers on the market
Comparison
- Specifications
- Efficiency
- Cost
- Availability
- Others
Recommendation

**Comment by Mike-Kimani** [comment]
@shohei The research findings are under the Michael folder. Please review.

**Comment by Mike-Kimani** [comment]
The research findings have been moved to MichaelResearch repo
 https://github.com/nakujaproject/MichaelResearch/tree/main/Accelerometer-Gyroscope%20research
