### ISSUE TITLE
Design and fabrication of parachute (N-1)

### ISSUE THREAD

**Issue by shohei** [nakujaproject/intern#3]

**Comment by dmashy** [comment]
Thank you Rodney for Uploading a possible parachute on the scrapbox:

I request that you:
Determine 1. the possible supplier and cost of the parachute in Kenya 2. Possible material in case we can buy locally the material and create it in-house or with the aid of a tailor.

Asante

**Comment by 0x6f736f646f** [comment]
- We discussed with @JeffMboya to fabricate our own parachute. 
- We have listed the possible materials and I will check on them tomorrow at our local supermarket.

**Comment by shohei** [comment]
@0x6f736f646f This is noted. Let me know what you found in the supermarket.

**Comment by dmashy** [comment]
Noted with thanks.

**Comment by shohei** [comment]
FYI: a guideline for sizing parachute
[Newsletter149 Properly Sizing Your Rockets.pdf](https://github.com/nakujaproject/intern/files/6082826/Newsletter149.pdf)

**Comment by dmashy** [comment]
Got it, thanks!

**Comment by 0x6f736f646f** [comment]
Done. ✅
