### ISSUE TITLE
Design of test stand

### ISSUE THREAD

**Issue by shohei** [nakujaproject/intern#32]
Ref: https://github.com/nakujaproject/intern/blob/main/felix/Nakuja%20internship%20Progress%20report%20format.pdf

**Comment by JeffMboya** [comment]
Test Stand design for N-1 rocket model  complete. 
![Test stand 1](https://user-images.githubusercontent.com/44696487/110314015-5c3cf000-8018-11eb-8c58-10399e8949f6.PNG)
![Test stand 2](https://user-images.githubusercontent.com/44696487/110314025-5f37e080-8018-11eb-8868-2d01ea722afa.PNG)
![Test Stand 3](https://user-images.githubusercontent.com/44696487/110314030-6101a400-8018-11eb-9e03-5df83467f66d.PNG)
![Test Stand 4](https://user-images.githubusercontent.com/44696487/110314037-6232d100-8018-11eb-94f5-30a790fb769b.PNG)
![Test stand 5](https://user-images.githubusercontent.com/44696487/110314040-63fc9480-8018-11eb-8aa9-b1f88ccdad45.PNG)
