### ISSUE TITLE
Casting of solid motor rocket propellant

### ISSUE THREAD

**Issue by shohei** [nakujaproject/intern#33]
Ref: https://github.com/nakujaproject/intern/blob/main/felix/Nakuja%20internship%20Progress%20report%20format.pdf

**Comment by 1998-felix** [comment]
- [ ] Research on solid moto rocket propellants preparation
- [ ] Acquisition of casting tools
- [ ] Design and simulation of grain performance
- [ ] Casting of the grains
- [ ] Testing

**Comment by 1998-felix** [comment]
first iteration of casting as been done
