### ISSUE TITLE
Design of N-1 rocket including determining which material is to be used to hold the cast propellant

### ISSUE THREAD

**Issue by shohei** [nakujaproject/intern#34]
Ref: https://github.com/nakujaproject/intern/blob/main/felix/Nakuja%20internship%20Progress%20report%20format.pdf

**Comment by SammyOina** [comment]
Pipe casing  (PVC) material comparison size 1.5''
Type | Schedule 40 | Schedule 80 
--- | --- | --- 
Inner Diameter (inches)| 1.592 | 1.476
Min Wall Thickness (inches)| 0.145 | 0.200
Max Working Pressure (psi)| 330 | 470
from https://www.jacobsrocketry.com/aer/misc_tables.htm

**Comment by SammyOina** [comment]
Pipe used for the casing
Material | UPVC
--- | ---
image | ![IMG_20210413_220830](https://user-images.githubusercontent.com/44265300/114608648-9304c680-9ca6-11eb-9549-44051683a912.jpg)
Pressure Nominal | 25
Outside Diameter | 40 mm
Inside Diameter | 31 mm
Wall thickness | 4.5mm
Estimated Design Pressure | 4.6MPa with a safety factor of 1.5
Burst Pressure | 12MPa with a d-safety factor of 2.62
