### ISSUE TITLE
Simulation of flight performance of N-1 rocket motor propellant

### ISSUE THREAD

**Issue by shohei** [nakujaproject/intern#35]
Ref: https://github.com/nakujaproject/intern/blob/main/felix/Nakuja%20internship%20Progress%20report%20format.pdf

**Comment by 1998-felix** [comment]
@0x6f736f646f  Please find attached a link to a motor .eng file please add it to open motor and present simulation data. https://github.com/nakujaproject/felixResearch/blob/main/Motor%20data/Motor150321-01/motor-36mm.eng

**Comment by shohei** [comment]
@1998-felix I have a question. How did you calculate the .eng data?

**Comment by 1998-felix** [comment]
@shohei I used openMotor to generate the thrust curves as well as the mass of propellant. I then calculated the mass of PPR pipe of length 90 mm as well as the weight of the nozzle. By inputting these parameters into openMotor I was able o generate a .eng file

**Comment by shohei** [comment]
@1998-felix Thank you for the clarification!

**Comment by SammyOina** [comment]
# Updated proposed N1-Motor
Grain diameter 40mm
performance | KNDX | KNSU 
--- | --- | ---
Designation | G47 | F46
Impulse | 85.83 | 70.26
Propellant mass (Kg) | 0.18 | 0.14
Average Pressure (MPa) | 1.38 | 1.36
Peak Pressure (MPa) | 1.52 | 1.49
Grain Length (mm) | 90 | 70
Core (mm) | 13 | 13
Nozzle (mm) | 9 | 9
Burn Time (s) | 1.77 | 1.47
Rasp File | [Eng File](https://github.com/nakujaproject/N1-motor/blob/main/Proposed%20Final%20Spec/N1-KNDX-proposed.eng) | [Eng File](https://github.com/nakujaproject/N1-motor/blob/main/Proposed%20Final%20Spec/N1-KNSU-proposed.eng) |
Thrust Curve | ![](https://github.com/nakujaproject/N1-motor/raw/main/Proposed%20Final%20Spec/KNDX.JPG) | ![](https://github.com/nakujaproject/N1-motor/raw/main/Proposed%20Final%20Spec/KNSU.JPG) |

**Comment by SammyOina** [comment]
> # Updated proposed N1-Motor
> Grain diameter 40mm
> 
> performance	KNDX	KNSU
> Designation	G47	F46
> Impulse	85.83	70.26
> Propellant mass (Kg)	0.18	0.14
> Average Pressure (MPa)	1.38	1.36
> Peak Pressure (MPa)	1.52	1.49
> Grain Length (mm)	90	70
> Core (mm)	13	13
> Nozzle (mm)	9	9
> Burn Time (s)	1.77	1.47
> Rasp File	[Eng File](https://github.com/nakujaproject/N1-motor/blob/main/Proposed%20Final%20Spec/N1-KNDX-proposed.eng)	[Eng File](https://github.com/nakujaproject/N1-motor/blob/main/Proposed%20Final%20Spec/N1-KNSU-proposed.eng)
> Thrust Curve	![](https://github.com/nakujaproject/N1-motor/raw/main/Proposed%20Final%20Spec/KNDX.JPG)	![](https://github.com/nakujaproject/N1-motor/raw/main/Proposed%20Final%20Spec/KNSU.JPG)

@0x6f736f646f Please find the Rasp file and simulate on openrocket for apogee simulation

**Comment by 0x6f736f646f** [comment]
> @0x6f736f646f Please find attached a link to a motor .eng file please add it to open Rocket and present simulation data. https://github.com/nakujaproject/felixResearch/blob/main/Motor%20data/Motor150321-01/motor-36mm.eng

Already tested it in openRocket.

**Comment by 0x6f736f646f** [comment]
> > # Updated proposed N1-Motor
> > Grain diameter 40mm
> > performance	KNDX	KNSU
> > Designation	G47	F46
> > Impulse	85.83	70.26
> > Propellant mass (Kg)	0.18	0.14
> > Average Pressure (MPa)	1.38	1.36
> > Peak Pressure (MPa)	1.52	1.49
> > Grain Length (mm)	90	70
> > Core (mm)	13	13
> > Nozzle (mm)	9	9
> > Burn Time (s)	1.77	1.47
> > Rasp File	[Eng File](https://github.com/nakujaproject/N1-motor/blob/main/Proposed%20Final%20Spec/N1-KNDX-proposed.eng)	[Eng File](https://github.com/nakujaproject/N1-motor/blob/main/Proposed%20Final%20Spec/N1-KNSU-proposed.eng)
> > Thrust Curve	![](https://github.com/nakujaproject/N1-motor/raw/main/Proposed%20Final%20Spec/KNDX.JPG)	![](https://github.com/nakujaproject/N1-motor/raw/main/Proposed%20Final%20Spec/KNSU.JPG)
> 
> @0x6f736f646f Please find the Rasp file and simulate on openrocket for apogee simulation

It has refused. Please use the format in the test folder. `.eng` should give the specs then `.csv` to give the thrust curve
