### ISSUE TITLE
Soldering of components on PCB

### ISSUE THREAD

**Issue by shohei** [nakujaproject/intern#38]
Ref: https://github.com/nakujaproject/intern/blob/main/ian/week%201%20report%20Nakuja.pdf

**Comment by oryankibandi** [comment]
![WhatsApp Image 2021-03-17 at 11 12 39 AM](https://user-images.githubusercontent.com/50994278/111442950-f3413080-8719-11eb-8553-d98c74162967.jpeg)
![WhatsApp Image 2021-03-17 at 12 10 06 PM](https://user-images.githubusercontent.com/50994278/111442962-f5a38a80-8719-11eb-9ce5-e45e9054ac12.jpeg)

**Comment by oryankibandi** [comment]
Components required:

- Attiny85
- 2 LEDs
- Switch
- Relay
- Buzzer
- Latching switch
- FC-75 battery charging board
- JST
