### ISSUE TITLE
Design of standard rocket motor test stand for both the N-1 rocket and N-2 rocket

### ISSUE THREAD

**Issue by shohei** [nakujaproject/intern#39]
Ref: https://github.com/nakujaproject/intern/blob/main/jeff/Nakuja%20internship%20Progress%20report%20format.pdf

**Comment by JeffMboya** [comment]
300mm * 250mm * 400 mm test stand deigned to accommodate both the small diameter N-1 rocket motor and 75mm N-2 rocket motor. 
![Test stand 2](https://user-images.githubusercontent.com/44696487/110315060-c4d89c80-8019-11eb-9773-341d30bff236.PNG)
![Test Stand 3](https://user-images.githubusercontent.com/44696487/110315064-c73af680-8019-11eb-82d9-e2c26b44d309.PNG)
![Test Stand 4](https://user-images.githubusercontent.com/44696487/110315069-c86c2380-8019-11eb-8862-7c86310bd4ef.PNG)
![Test stand 5](https://user-images.githubusercontent.com/44696487/110315072-c99d5080-8019-11eb-9a58-69de53b9d285.PNG)
![Test stand 1](https://user-images.githubusercontent.com/44696487/110315074-cace7d80-8019-11eb-9922-aca0451f834b.PNG)
