### ISSUE TITLE
Fabrication of the designed test stand

### ISSUE THREAD

**Issue by shohei** [nakujaproject/intern#40]
Ref: https://github.com/nakujaproject/intern/blob/main/jeff/Nakuja%20internship%20Progress%20report%20format.pdf

**Comment by JeffMboya** [comment]
Test stand Progress. 
![WhatsApp Image 2021-03-19 at 16 15 45](https://user-images.githubusercontent.com/44696487/111786302-b4a0a700-88ce-11eb-971d-6450765a36b3.jpeg)

**Comment by shohei** [comment]
Close this issue as the same task (#1) was closed
