### ISSUE TITLE
Tapping of the rocket motor nozzle, casing, and bulk head.

### ISSUE THREAD

**Issue by shohei** [nakujaproject/intern#41]
Ref: https://github.com/nakujaproject/intern/blob/main/jeff/Nakuja%20internship%20Progress%20report%20format.pdf

**Comment by JeffMboya** [comment]
Tapping of the rocket motor nozzle, casing, and bulk head done. 
![IMG_20210304_094219_6](https://user-images.githubusercontent.com/44696487/110314659-3237fd80-8019-11eb-974f-53cbd6cce725.jpg)
![IMG_20210304_094220_3](https://user-images.githubusercontent.com/44696487/110314673-36641b00-8019-11eb-902b-4aa98c402692.jpg)
