### ISSUE TITLE
Research on STM-32 blue pill

### ISSUE THREAD

**Issue by shohei** [nakujaproject/intern#44]
Ref: https://github.com/nakujaproject/intern/blob/main/michael/Nakuja%20internship%201st%20week%20Progress%20report%20.pdf

**Comment by Mike-Kimani** [comment]
Basic instructions on how to use the STM32 blue pill can be found [here](https://github.com/nakujaproject/MichaelResearch/tree/main/STM32%20BLUEPILL%20RESEARCH)
