### ISSUE TITLE
Research on the MPU6050

### ISSUE THREAD

**Issue by shohei** [nakujaproject/intern#47]
Ref: https://github.com/nakujaproject/intern/blob/main/michael/Nakuja%20internship%201st%20week%20Progress%20report%20.pdf

**Comment by 0x6f736f646f** [comment]
@Mike-Kimani Check [this](https://github.com/TKJElectronics/KalmanFilter) out

**Comment by Mike-Kimani** [comment]
Thank you @0x6f736f646f

**Comment by 0x6f736f646f** [comment]
Also [this](https://github.com/CosmicResearch/Ansari2019)

**Comment by 0x6f736f646f** [comment]
> Thank you @0x6f736f646f

Welcome

**Comment by 0x6f736f646f** [comment]
@oryankibandi Did you finish this?
Please report with a documentation
