### ISSUE TITLE
Programming the BPM 180

### ISSUE THREAD

**Issue by shohei** [nakujaproject/intern#48]
Ref: https://github.com/nakujaproject/intern/blob/main/michael/Nakuja%20internship%201st%20week%20Progress%20report%20.pdf

**Comment by Mike-Kimani** [comment]
Done. Please review @shohei 
Find the code here https://github.com/nakujaproject/avionicsv1/tree/main/BMP180

**Comment by 0x6f736f646f** [comment]
[demo](https://randomnerdtutorials.com/guide-for-bmp180-barometric-sensor-with-arduino/)

**Comment by shohei** [comment]
> Done. Please review @shohei
> Find the code here https://github.com/nakujaproject/avionicsv1/tree/main/BMP180

The code seems to be okay. I'd like to see the graph plot to check the error/noise.

**Comment by shohei** [comment]
> [demo](https://randomnerdtutorials.com/guide-for-bmp180-barometric-sensor-with-arduino/)

@0x6f736f646f 
Is the demo correct? I found an article on the site, not a demo.

**Comment by 0x6f736f646f** [comment]
@Mike-Kimani and I tried it but it failed to work

**Comment by 0x6f736f646f** [comment]
For streaming data from arduino to excel, have a look at [this](https://create.arduino.cc/projecthub/HackingSTEM/stream-data-from-arduino-into-excel-f1bede)

**Comment by 0x6f736f646f** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=56976

**Comment by Mike-Kimani** [comment]
Thank you @0x6f736f646f

**Comment by 0x6f736f646f** [comment]
1. [Moving average ](https://maker.pro/arduino/tutorial/how-to-clean-up-noisy-sensor-data-with-a-moving-average-filter) with three window sizes
2. [Exponential average](https://www.megunolink.com/documentation/arduino-libraries/exponential-filter/)
3. [Digital smooth](https://playground.arduino.cc/Main/DigitalSmooth/)
4. [Running median](https://playground.arduino.cc/Main/RunningMedian/)
5. [fir and iir filters](https://github.com/jeroendoggen/Arduino-signal-filtering-library/tree/master/Filter/examples)

**Comment by Mike-Kimani** [comment]
Let me do this

**Comment by 0x6f736f646f** [comment]
Done
