### ISSUE TITLE
Development of Avionics bay (N-1)

### ISSUE THREAD

**Issue by shohei** [nakujaproject/intern#5]
Avionics bay for N-1 requires the following functions

- [x] Preliminary research (#20)
  - [x] Altimeter
  - [x] Accelerometer
  - [x] Gyroscope
  - [ ] Others
- [x] Programming (#21)
- [ ] Detection of apogee (#22)
- [x] Parachute ejection (#22)
- [ ] Fabrication of avionics bay (#23)

**Comment by 0x6f736f646f** [comment]
For the mechanical part check out [this](https://github.com/nakujaproject/airframev1/blob/main/Design/electronicsbay.stl)

The electronics PCB will be able to be screwed on the avionic bay

For refinement the avionics team should be able to:

- [ ] Place the components on one PCB
- [ ] The back will be an attachment for the battery pack
- [ ] The PCB should have drill holes to be able to secure it correctly to the avionics bay
- [ ] Provide the actual length and width of the  #PCB

**Comment by 0x6f736f646f** [comment]
I am currently printing the [avionics bay](https://github.com/nakujaproject/airframev1/blob/main/Design/electronicsbay.pdf) where the @nakujaproject/avionics-group will house their components

**Comment by 0x6f736f646f** [comment]
![Screenshot 2021-03-23 18 47 45](https://user-images.githubusercontent.com/28790446/112175584-69f19880-8c08-11eb-8649-522484838520.png)

**Comment by Mike-Kimani** [comment]
@0x6f736f646f    What should be the diameter of the mounting holes on the PCB?

**Comment by 0x6f736f646f** [comment]
1 mm
