### ISSUE TITLE
Research on parachute ejection mechanism

### ISSUE THREAD

**Issue by shohei** [nakujaproject/intern#50]
Ref: https://github.com/nakujaproject/intern/blob/main/michael/Nakuja%20internship%201st%20week%20Progress%20report%20.pdf

**Comment by 0x6f736f646f** [comment]
The parent issue #22

**Comment by 0x6f736f646f** [comment]
@dmashy Please review https://github.com/nakujaproject/rodneyResearch/blob/main/Airfrane/01parachuteEjection.md

**Comment by 0x6f736f646f** [comment]
- I am awaiting the avionics team @Mike-Kimani
- The nose cone for testing has been fabricated and ready for testing

![image](https://user-images.githubusercontent.com/28790446/110753295-77e20980-8257-11eb-90df-3d8a82bc9c71.png)

**Comment by 0x6f736f646f** [comment]
- [x] Research on ejection mechanism done ✅

**Comment by 0x6f736f646f** [comment]
Next we will be implementing the mechanism
