### ISSUE TITLE
Research on parachute design

### ISSUE THREAD

**Issue by shohei** [nakujaproject/intern#51]
Ref: https://github.com/nakujaproject/intern/blob/main/michael/Nakuja%20internship%201st%20week%20Progress%20report%20.pdf

**Comment by 0x6f736f646f** [comment]
The parent issue is #52

**Comment by 0x6f736f646f** [comment]
@JeffMboya and @dmashy Check and proof read literatutre at [here](https://github.com/nakujaproject/rodneyResearch/blob/main/Airfrane/02recoveryMechanism.md)

**Comment by 0x6f736f646f** [comment]
CLosing the issue as it has been completed.
