### ISSUE TITLE
Make parachute

### ISSUE THREAD

**Issue by shohei** [nakujaproject/intern#52]
Ref: https://github.com/nakujaproject/intern/blob/main/rodney/01032021-05032021internshipProgressreport.pdf

**Comment by 0x6f736f646f** [comment]
## Progress

- [x] Parachute testing done
- [x] Research on parachute done

https://user-images.githubusercontent.com/28790446/110754143-83820000-8258-11eb-914d-b679e435f094.mp4

**Comment by 0x6f736f646f** [comment]
The issue has been done. We will continue testing with the avionics team for ejection mechanism
