### ISSUE TITLE
Start designing the new model rocket

### ISSUE THREAD

**Issue by shohei** [nakujaproject/intern#53]
Ref: https://github.com/nakujaproject/intern/blob/main/rodney/01032021-05032021internshipProgressreport.pdf

**Comment by 0x6f736f646f** [comment]
Closing issue since it is the same as #16.

I will be working with reference with it.

For reference check out :

1. [Openrocket design](https://github.com/nakujaproject/airframe_openrocket)
2. [Inventor design](https://github.com/nakujaproject/airframev1)
