### ISSUE TITLE
Research on avionics components needed

### ISSUE THREAD

**Issue by shohei** [nakujaproject/intern#54]
Ref: https://github.com/nakujaproject/intern/blob/main/rodney/01032021-05032021internshipProgressreport.pdf

**Comment by 0x6f736f646f** [comment]
Also related issues are #20 #23 #48 #47

**Comment by 0x6f736f646f** [comment]
@Mike-Kimani @oryankibandi Review and add suggested changes https://github.com/nakujaproject/rodneyResearch/blob/main/Avionics/01researchAvionics.md
