### ISSUE TITLE
Program to analyze thrust data for N-1 motor

### ISSUE THREAD

**Issue by shohei** [nakujaproject/intern#58]
Ref: https://github.com/nakujaproject/intern/blob/main/sammy/week%201.pdf

**Comment by shohei** [comment]
Maybe related to #2 ?

**Comment by SammyOina** [comment]
> Maybe related to #2 ?

Yes they are relted

**Comment by SammyOina** [comment]
- [ ] Read data from serial port
- [ ] Calculated total impulse, specific impulse, average thrust from CSV file
- [ ] Real-time graphing of data with Grafana and influxdb
- [ ] Upload csv file to google drive

**Comment by SammyOina** [comment]
see [https://github.com/nakujaproject/thrust-analysis](url)
