### ISSUE TITLE
Finishing N-2 casing fabrication

### ISSUE THREAD

**Issue by shohei** [nakujaproject/intern#7]

**Comment by shohei** [comment]
> @Tim and @Jeff Mboya have just finished drilling holes on the casing cylinder body. Tomorrow we'll finish on drilling and tapping on the nozzle and bulk head
<img src="https://user-images.githubusercontent.com/855816/109500827-cf3de800-7aa7-11eb-93b6-6fa0b53ddfd0.png" width=200px>

**Comment by SammyOina** [comment]
O-rings for n2 nozzle and bulkhead ![MVIMG_20210329_212001](https://user-images.githubusercontent.com/44265300/112881941-fef70480-90d4-11eb-9de9-e7f1f17f95a1.jpg)

**Comment by SammyOina** [comment]
![WhatsApp Image 2021-03-30 at 21 17 38](https://user-images.githubusercontent.com/44265300/113036943-8445ec00-919d-11eb-9062-3f9b1b368194.jpeg)
O-rings groves have been machined and the motor has been assembled making the motor ready for static firing
