### ISSUE TITLE
Read acceleration and orientation from MPU6050

### ISSUE THREAD

**Issue by oryankibandi** [nakujaproject/intern#70]
This tasks involves reading the values of acceleration and orientation from the MPU6050.

**Comment by 0x6f736f646f** [comment]
Check out [this](https://github.com/denyssene/SimpleKalmanFilter/blob/master/examples/BasicKalmanFilterExample/BasicKalmanFilterExample.ino)

**Comment by 0x6f736f646f** [comment]
@Mike-Kimani Are we done with this?

Reference to working [prototype](https://github.com/nakujaproject/avionicsv1/commit/7f05e97300eade009384921e2985c8807d545310)

**Comment by 0x6f736f646f** [comment]
@oryankibandi and @Mike-Kimani please close this since we are done with it
