### ISSUE TITLE
Data loggin2

### ISSUE THREAD

**Issue by Mike-Kimani** [nakujaproject/intern#72]
ESP 32 On-board flash memory.

Report on:
1. Efficiency
2. Reliability
3. Programming

Put findings in the avionicsV1 repo

**Comment by oryankibandi** [comment]
https://randomnerdtutorials.com/esp32-flash-memory/

**Comment by 0x6f736f646f** [comment]
@Mike-Kimani are we done with this?

**Comment by Mike-Kimani** [comment]
Yes we decided to go with an sdcard for data logging purposes
