### ISSUE TITLE
SPI flash memory

### ISSUE THREAD

**Issue by Mike-Kimani** [nakujaproject/intern#73]
Report on:

1. Efficiency
2. Ease of use
3. Availability of flash memory chips

**Comment by 0x6f736f646f** [comment]
@Mike-Kimani are we done with this?

**Comment by 0x6f736f646f** [comment]
@Mike-Kimani I think we will be using and external SD card for memory

**Comment by 0x6f736f646f** [comment]
@Mike-Kimani Please close completed issues
