### ISSUE TITLE
Test ejection mechanism

### ISSUE THREAD

**Issue by 0x6f736f646f** [nakujaproject/intern#79]
## Expected Behavior
To safely eject the parachute on flight

## Actual Behavior
The current ejection mechanism failed

## Steps to Reproduce the Problem
Assemble the nose cone and body and test the ejection mechanism

## Specifications
  - Platform: Airframe
  - Servo: Micro servo
  - Timer - 6 seconds
  - Flight time - 1 second
  - Height - SPA to floor

**Comment by JeffMboya** [comment]
Time-actuated parachute ejection mechanism tested twice. First test failed. Second test was successful. More tests and modification to be conducted to ascertain reliability @0x6f736f646f

**Comment by 0x6f736f646f** [comment]
👍🏾

**Comment by 0x6f736f646f** [comment]
Done
