### ISSUE TITLE
Casting propellant (fuel and oxidizer)

### ISSUE THREAD

**Issue by shohei** [nakujaproject/intern#8]
- Casting fuel for the experiment on the N-1 rocket 
  - Use electric heater, spatula, and pan
<img src="https://user-images.githubusercontent.com/855816/109496917-5ab47a80-7aa2-11eb-857c-fb8e3dcd8208.png" alt="drawing" width="200"/>

**DO NOT FULLY PACK THE N-2 CASING AND FIRE. ENERGY IS TOO HIGH FOR THE EXPERIMENT**
- Better to start from small portion (less than 100g)

**Comment by SammyOina** [comment]
https://youtu.be/seHl_T3TNuw
