### ISSUE TITLE
Development of SRM static firing nozzle

### ISSUE THREAD

**Issue by 1998-felix** [nakujaproject/intern#84]

**Comment by SammyOina** [comment]
![image](https://user-images.githubusercontent.com/44265300/116138175-25f92400-a6dd-11eb-957f-c9b2c783b39d.png)

**Comment by SammyOina** [comment]
The concrete to be used
![IMG_20210426_221552](https://user-images.githubusercontent.com/44265300/116138264-445f1f80-a6dd-11eb-9a5a-3cc882f49377.jpg)
